spring:
  datasource:
    url: jdbc:sqlite:${user.home}/.smartfilemanager/smart_file_manager.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    properties:
        hibernate:
          format_sql: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: trace


# AI配置
ai:
  xunfei:
    app-id: "1715d985"
    api-secret: "ZDczMjdiZTIxZjZjZmY5NTlhZDQ4YzU3"
    api-key: "688c20b431c0e59122e54c5e1a8e6b24"
    host-url: "wss://spark-api.xf-yun.com/x2"
    domain: "spark-x"
    temperature: 0.5
    max-tokens: 4096